### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by Cyrgia** [FalsePhilosopher/PPPwnWRT#1]
Hello,
I tried each line of the script pppwnwrt11.sh, and i tried to launch:
pppwn --interface lan1 --fw 1100 --stage1 "/etc/PPPwnWRT/stage1.bin" --stage2 "/etc/PPPwnWRT/stage2.bin" --auto-retry
Without adding it in rc.local, but i get this error:
/bin/pppwn: line 1: syntax error: unexpected word (expecting ")")
I get this error even if I just run pppwn

My OpenWRT firmware Version is: OpenWrt 23.05.2 r23630-842932a63d / LuCI openwrt-23.05 branch git-23.306.39416-c86c256

Is this normal?
Thanks

**Comment by manos555555** [comment]
same here!

**Comment by FalsePhilosopher** [comment]
I added more architectures to the repo, so now you should be able to pull whatever is supported on your router.

**Comment by Cyrgia** [comment]
i've already test other bin with no success, i think i got an other architecture that is not compile by xfangfang (mips_24kc from openWRT techdata).
i think i have to wait for it
thanks to you anyway

**Comment by FalsePhilosopher** [comment]
> i've already test other bin with no success, i think i got an other architecture that is not compile by xfangfang (mips_24kc from openWRT techdata). i think i have to wait for it thanks to you anyway

You can always try to cross compile it for mips_24kc and throw it in /bin as a drop in replacement.

**Comment by Cyrgia** [comment]
if I knew how to do it, I would have done it already :)

**Comment by kondratovicz** [comment]
hi, you can try this 
https://github.com/xfangfang/PPPwn_cpp/issues/28

**Comment by FalsePhilosopher** [comment]
This is a pppwn_cpp issue and not a PPPwnWRT issue.
