### ISSUE TITLE
Stuck at ipcp configure ack

### ISSUE THREAD

**Issue by S1keman215** [FalsePhilosopher/PPPwnWRT#13]
Im using open wrt version 21.02.01 stuck at ipcp configure ack

[+] args: interface=br-lan fw=1100 stage1=/etc/pppwnwrt/stage1_1100.bin stage2=/etc/pppwnwrt/stage2.bin timeout=0 wait-after-pin=1 groom-delay=4 auto-retry=on no-wait-padi=off real_sleep=off

[+] STAGE 0: Initialization
[*] Waiting for PADI...
[*] Waiting for PADI...
[+] pppoe_softc: 0xffff97f80799da00
[+] Target MAC: 0c:fe:45:a5:cd:20
[+] Source MAC: 07:da:99:07:f8:97
[+] AC cookie length: 4e0
[*] Sending PADO...
[*] Waiting for PADR...
[*] Sending PADS...
[*] Sending LCP configure request...
[*] Waiting for LCP configure ACK...
[*] Waiting for LCP configure request...
[*] Sending LCP configure ACK...
[*] Sending IPCP configure request...
[*] Waiting for IPCP configure ACK...
[*] Waiting for IPCP configure request...
[*] Sending IPCP configure NAK...
[*] Waiting for IPCP configure request...
[*] Sending IPCP configure ACK...
[*] Waiting for interface to be ready...
[+] Target IPv6: fe80::efe:45ff:fea5:cd20

[*] Heap grooming...0%
[*] Heap grooming...6%
[*] Heap grooming...12%
[*] Heap grooming...18%
[*] Heap grooming...25%
[*] Heap grooming...31%
[*] Heap grooming...37%
[*] Heap grooming...43%
[*] Heap grooming...50%
[*] Heap grooming...56%
[*] Heap grooming...62%
[*] Heap grooming...68%
[*] Heap grooming...75%
[*] Heap grooming...81%
[*] Heap grooming...87%
[*] Heap grooming...93%
[+] Heap grooming...done

[+] STAGE 1: Memory corruption

[*] Pinning to CPU 0...00%
[*] Pinning to CPU 0...06%
[*] Pinning to CPU 0...12%
[*] Pinning to CPU 0...18%
[*] Pinning to CPU 0...25%
[*] Pinning to CPU 0...31%
[*] Pinning to CPU 0...37%
[*] Pinning to CPU 0...43%
[*] Pinning to CPU 0...50%
[*] Pinning to CPU 0...56%
[*] Pinning to CPU 0...62%
[*] Pinning to CPU 0...68%
[*] Pinning to CPU 0...75%
[*] Pinning to CPU 0...81%
[*] Pinning to CPU 0...87%
[*] Pinning to CPU 0...93%
[+] Pinning to CPU 0...done
[*] Sending malicious LCP configure request...
[*] Waiting for LCP configure reject...
[*] Sending LCP configure request...
[*] Waiting for LCP configure ACK...
[*] Waiting for LCP configure request...
[*] Sending LCP configure ACK...
[*] Sending IPCP configure request...
[*] Waiting for IPCP configure ACK...
[*] Waiting for IPCP configure request...
[*] Sending IPCP configure NAK...
[*] Waiting for IPCP configure request...
[*] Sending IPCP configure ACK...

[*] Scanning for corrupted object... 0xf00
[*] Scanning for corrupted object... 0xe00
[*] Scanning for corrupted object... 0xd00
[*] Scanning for corrupted object... 0xc00
[*] Scanning for corrupted object... 0xb00
[*] Scanning for corrupted object... 0xa00
[*] Scanning for corrupted object... 0x900
[*] Scanning for corrupted object... 0x800
[*] Scanning for corrupted object... 0x700
[*] Scanning for corrupted object... 0x600
[*] Scanning for corrupted object... 0x500
[*] Scanning for corrupted object... 0x400
[*] Scanning for corrupted object... 0x300
[*] Scanning for corrupted object... 0x200
[*] Scanning for corrupted object... 0x100
[+] Scanning for corrupted object...found fe80::007f:4141:4141:4141

[+] STAGE 2: KASLR defeat

[*] Defeating KASLR...
[+] pppoe_softc_list: 0xffffffffdbf7a578
[+] kaslr_offset: 0x57a98000

[+] STAGE 3: Remote code execution
[*] Sending LCP terminate request...
[*] Waiting for PADI...
[+] pppoe_softc: 0xffff97f80799da00
[+] Target MAC: 0c:fe:45:a5:cd:20
[+] Source MAC: 97:9f:94:da:ff:ff
[+] AC cookie length: 510
[*] Sending PADO...
[*] Waiting for PADR...
[*] Sending PADS...
[*] Triggering code execution...
[*] Waiting for stage1 to resume...
[*] Sending PADT...
[*] Waiting for PADI...
[+] pppoe_softc: 0xffff97f80799da00
[+] Target MAC: 0c:fe:45:a5:cd:20
[+] AC cookie length: 0
[*] Sending PADO...
[*] Waiting for PADR...
[*] Sending PADS...
[*] Sending LCP configure request...
[*] Waiting for LCP configure ACK...
[*] Waiting for LCP configure request...
[*] Sending LCP configure ACK...
[*] Sending IPCP configure request...
[*] Waiting for IPCP configure ACK...

Any solution ??

**Comment by tongduanmingo** [comment]
btw its normal sometimes its stuck sometime its finish so don't worry kill the pid and re-run
which router you are using this may because of low-end hardware

**Comment by S1keman215** [comment]
Im using bolt bl201

**Comment by FalsePhilosopher** [comment]
This is a pppwn_cpp issue and not a PPPwnWRT issue.
