### ISSUE TITLE
Stage 1: system_error: thread constructor failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by Greengoblin007** [FalsePhilosopher/PPPwnWRT#14]
Hi all,

I am running pppwnwrt on a very old router, La Fonera+ from 2007. 16 MB of RAM, 8 MB of flash and a MIPS processor.

I got the aforementioned error as soon as I reach Stage 1. ChatGPT suggests it may be related to hardware limitations.

So my question is, which are the absolutely minimum system requirements to run this software?

May uninstall unused services relieve some RAM and processor workload and make it work?

I can provide more context if necessary.

Thank you and regards.

PS: the complete error says "libc++abi: terminating due to uncaught exception of type std::__1::system_error: thread constructor failed: Resource temporarily unavailable Aborted"

**Comment by Greengoblin007** [comment]
I'll try this later:

https://github.com/xfangfang/PPPwn_cpp/issues/61

And let you all know the results.

**Comment by Greengoblin007** [comment]
> I'll try this later:
> 
> [xfangfang/PPPwn_cpp#61](https://github.com/xfangfang/PPPwn_cpp/issues/61)
> 
> And let you all know the results.

No, it does not work either.

**Comment by SyderaLGaming** [comment]
> > I'll try this later:
> > [xfangfang/PPPwn_cpp#61](https://github.com/xfangfang/PPPwn_cpp/issues/61)
> > And let you all know the results.
> 
> No, it does not work either.

Check now, xfangfang resolve

**Comment by SyderaLGaming** [comment]
> > I'll try this later:
> > [xfangfang/PPPwn_cpp#61](https://github.com/xfangfang/PPPwn_cpp/issues/61)
> > And let you all know the results.
> 
> No, it does not work either.


try --real-sleep -bs 10240, it worked for me

**Comment by FalsePhilosopher** [comment]
This is a pppwn_cpp issue and not a PPPwnWRT issue.
