### ISSUE TITLE
 How can I create a script to turn off the router after running pppwn?

### ISSUE THREAD

**Issue by SyderaLGaming** [FalsePhilosopher/PPPwnWRT#16]
This pppwn auto-start process really works very well for me, but I have seen in other repositories that they install a script to turn off the router after the pppwn process has been executed. Could someone help me with this?

Thanks in advance

sorry my bad english ( google traslate)

**Comment by FalsePhilosopher** [comment]
edit /etc/init.d/pppwnwrt
`procd_set_param command sh /etc/pppwnwrt/pppwnwrt.sh && shutdown -h now`
