### ISSUE TITLE
DD-WRT issue

### ISSUE THREAD

**Issue by sasiccia84** [FalsePhilosopher/PPPwnWRT#17]
Hi! 

I tried following the instructions for dd-wrt but, as per it's design I cannot copy to /etc or /bin as they are mounted as read only, The only folders I can copy to are:

jffs
tmp
usr
var

I can also copy the pppwnwrt folder, but not its content, into dev... If that helps. 

can you please suggest a solution? 

Thanks a lot! 

Sasiccia

**Comment by FalsePhilosopher** [comment]
Try mounting an external usb drive with everything on it and setup the auto start to read from that location, you can try installing openwrt, ssh in as root and remount the drive as RW, idk if dd-wrt has an fstab file but modify that to mount the partition as RW.

**Comment by FalsePhilosopher** [comment]
Placing things in /etc or /bin are not necessary either, where ever you can place the executable and the payloads will work.
