### ISSUE TITLE
/bin/pppwn: line 6: syntax error: unexpected "|"

### ISSUE THREAD

**Issue by JonJonSalchichon** [FalsePhilosopher/PPPwnWRT#18]
While trying to set up PPPwnWRT on Huawei EchoLife HG5556a rev.C with OpenWRT 23.05.0

After using MIPS build command in Putty:

wget -q -O - https://github.com/FalsePhilosopher/PPPwnWRT/raw/main/scripts/MIPS.sh | sh

seems to be an issue with MIPS.sh line 11 = pppwn list

Error displayed as per title: /bin/pppwn: line 6: syntax error: unexpected "|"

![MIPS sh](https://github.com/FalsePhilosopher/PPPwnWRT/assets/108337179/aa10329a-014a-4573-809e-2d9f0aeb6afc)

Could somebody help?

**Comment by speedyes** [comment]
It doesn't want to replace updated files for some reason. Try deleting '/etc/init.d/pppwnwrt' and '/bin/pppwn'

**Comment by lichtmetzger** [comment]
Seems to be a general issue with the script. It doesn't handle replacing already existing files properly.

```
Redirected to /FalsePhilosopher/PPPwnWRT/main/zips/CortexA7.zip on raw.githubusercontent.com
Writing to 'CortexA7.zip'
CortexA7.zip         100% |*******************************|   388k  0:00:00 ETA
Download completed (397456 bytes)
Archive:  files.zip
replace /etc/init.d/pppwnwrt? [y]es, [n]o, [A]ll, [N]one, [r]ename: error:  invalid response [ables! \e]
replace /etc/init.d/pppwnwrt? [y]es, [n]o, [A]ll, [N]one, [r]ename: error:  invalid response [[0m"]
replace /etc/init.d/pppwnwrt? [y]es, [n]o, [A]ll, [N]one, [r]ename: error:  invalid response [echo ""]
replace /etc/init.d/pppwnwrt? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
Archive:  CortexA7.zip
replace /bin/pppwn? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
```

Deleting the mentioned directories and then running it works.
