### ISSUE TITLE
PS4 can't find IP address and nothing pops up

### ISSUE THREAD

**Issue by speedyes** [FalsePhilosopher/PPPwnWRT#2]
Title, installed for MIPS architecture and PS4 is connected to LAN1 port. Tried restarting the router with no success. I didn't configure my router in any way besides root password and enabling SSH. Are there any logs available? I'm not very familiar with OpenWRT

**Comment by speedyes** [comment]
I managed to solve it partially. Script by default comes with wrong pre-configured interface for my router (I have eth0.1), however it doesn't boot automatically. I need to login to SSH and start it from there to run the script. Any clue what might be wrong?

**Comment by speedyes** [comment]
So I solved it by adding "pppwn --interface eth0.1 --fw 1100 --stage1 "/etc/PPPwnWRT/stage1.bin" --stage2 "/etc/PPPwnWRT/stage2.bin" --auto-retry&" (notice "&" at the end) to System --> Startup --> Local Startup. The only issue is: my PS4 crashed four times already with zero successes! I'll try to replace stage2.bin with GoldHEN release from github

**Comment by speedyes** [comment]
I replaced stage1.bin with one from PPPwn GUI 1.7 and stage2.bin with one from GoldHEN's github release. I reverted to original init.d configuration too. I changed `START=` line to 97, just after LEDs initialization and works perfectly now without any crash and starts at router's boot, but it appears that script runs only once and then exits. I'll try to fix that and post here how I did that

**Comment by FalsePhilosopher** [comment]
It's been a min since I played with an init.d script with openwrt, it says it's enabled and runs with start but won't run at boot for whatever reason. So I just removed all that noise as I have a life outside of trying to grind away at whatever stupid config it wants. Feel free to PR an init.d scripted version if you get that working.

**Comment by speedyes** [comment]
Nah still crashes, I will test with my stage files and try to rework init to make it run even when it succeeds

**Comment by FalsePhilosopher** [comment]
It seems xfangfang is still working on the mips version, so hang tight for a min while they work on it and update your executable in /bin when that gets hammered out.

**Comment by speedyes** [comment]
fixed with new stage1.bin
