### ISSUE TITLE
Stuck on waiting for PADR issue

### ISSUE THREAD

**Issue by mahmodlte** [FalsePhilosopher/PPPwnWRT#21]
Hi @FalsePhilosopher. I have an issue with the openwrt router setup. I have a devolo magic 2 wifi next with Openwrt 21.  I setup everything correctly but the jailbreak doesn't work. and I have been trying to check the issue and still didn't get what is going on. I have tried to run the script from SSH manually and I found out that it gets stuck at waiting for PADR in stage 1. and the PS4 doesn't get an IP address even  though the script finds the target mac address. This is a photo from the SSH running the script
![image](https://github.com/FalsePhilosopher/PPPwnWRT/assets/5852876/149237f0-17b7-4922-a506-4a6bf8955270)

**Comment by FalsePhilosopher** [comment]
This is an issue with pppwn_cpp and not pppwnwrt, you might be running the 1.0 release and have one of those "cursed consoles". So try the nightly build and if that doesn't work open an issue in pppwn_cpp.

**Comment by mahmodlte** [comment]
Thank you so much I appreciate it. I will try to use the latest release. and see how
