### ISSUE TITLE
Issue with TL-MR3420

### ISSUE THREAD

**Issue by sasiccia84** [FalsePhilosopher/PPPwnWRT#24]
Hi all!
I am trying to setup my OpenWRT router for pppwn, unfortunately I cannot use the automatic script for storage reasons.

So now i have pppwn executable in the /bin folder
i have the pppwnwrt folder with stage1 and stage2 (These are those I took  from a conversation, are they different from architecture to architecture?) in the /etc folder
I have installed libpcap 
Then I've ran pppwn
but I get the following error message:
/bin/pppwn: line 1: syntax error: unexpected word (expecting ")")
What am I doing wrong?

Thanks a lot for your help!

S.

**Comment by FalsePhilosopher** [comment]
What you're doing wrong is not providing any type of logging to actually solve your issue, it sounds like how you tried to execute pppwn or it's the wrong architecture and try a different bin.

**Comment by sasiccia84** [comment]
[![image.png](https://i.postimg.cc/hjdLtc5m/image.png)](https://postimg.cc/wy9yW8Hx)

I was using the wrong executable, mipsel instead of mips, there are no mips files in the links posted in the tutorial.

The command that worked for me was:
pppwn -i br-lan --fw 1100 -s1 "/etc/pppwnwrt/stage1.bin" -s2 "/etc/pppwnwrt/stage2.bin" -a
But I might have the interface, that "br-lan" wrong
the script works
I'll have to test it with the ps4 later

**Comment by FalsePhilosopher** [comment]
👍
