### ISSUE TITLE
It says done but nothing on ps4

### ISSUE THREAD

**Issue by lpzrulez** [FalsePhilosopher/PPPwnWRT#4]
Hello
Thanks for this amazing tutorial 
I changed stage2.bin with the goldhen.bin (renaming it of course)As the Orignal setup just gave pppwned message on screen

But the problem is 

[*] Sending stage2 payload...
[+] Done!

It states this but the goldhen isn’t loaded on the ps4 
What am I doing wrong please help

**Comment by FalsePhilosopher** [comment]
I guess I should have added the USB drive info but figured this repo was not the first they came across and was familiar with the process.

1. Place the goldhen.bin from a golden 2.4b17 and up release on the root of a usb drive formatted in exfat or fat32
https://github.com/GoldHEN/GoldHEN/releases/download/2.4b17/GoldHEN_v2.4b17.7z
2. Plug the USB drive into your PS4
3. Run pppwn again

**Comment by lpzrulez** [comment]
Do I need to rename the goldhen.bin file or it is not needed
