### ISSUE TITLE
Getting "Killed" when running PPPwnWRT

### ISSUE THREAD

**Issue by ukyo13** [FalsePhilosopher/PPPwnWRT#6]
I've tried following the guide and PPPwnWRT is installed, and I can have it run "pppwn list" to show the interfaces. When I've tried running the below script though, it gives me a "Killed" notification just a few seconds after running.
"pppwn --interface eth0.1 --fw 1100 --stage1 "/etc/PPPwnWRT/stage1.bin" --stage2 "/etc/PPPwnWRT/stage2.bin" --auto-retry"

I'm using an Asus RT-N12+ B1 and have used the MIPS build

**Comment by FalsePhilosopher** [comment]
> I've tried following the guide and PPPwnWRT is installed, and I can have it run "pppwn list" to show the interfaces. When I've tried running the below script though, it gives me a "Killed" notification just a few seconds after running. "pppwn --interface eth0.1 --fw 1100 --stage1 "/etc/PPPwnWRT/stage1.bin" --stage2 "/etc/PPPwnWRT/stage2.bin" --auto-retry"
> 
> I'm using an Asus RT-N12+ B1 and have used the MIPS build

Please provide the SSH log of when you try to run pppwn.

**Comment by ukyo13** [comment]
> > I've tried following the guide and PPPwnWRT is installed, and I can have it run "pppwn list" to show the interfaces. When I've tried running the below script though, it gives me a "Killed" notification just a few seconds after running. "pppwn --interface eth0.1 --fw 1100 --stage1 "/etc/PPPwnWRT/stage1.bin" --stage2 "/etc/PPPwnWRT/stage2.bin" --auto-retry"
> > I'm using an Asus RT-N12+ B1 and have used the MIPS build
> 
> Please provide the SSH log of when you try to run pppwn. xfangfang is working on the MIPS build and this might require a future update to pppwn_cpp.

It just shows the args of pppwn then immediately says "Killed", no other ssh logs

**Comment by FalsePhilosopher** [comment]
Posting a description of the log instead of the actual log does nobody any good and we can't help you until you can post an actual log.

**Comment by ukyo13** [comment]
> Posting a description of the log instead of the actual log does nobody any good and we can't help you until you can post an actual log.

My bad, I've already turned off my PS4 and PC when I replied. I'll try later and send the actual SSH logs

**Comment by ukyo13** [comment]
![image_2024-05-21_181422191](https://github.com/FalsePhilosopher/PPPwnWRT/assets/15646143/defd1998-03a3-413d-9394-51878708efaa)

I've retried again today. Here's the full log from putty

**Comment by FalsePhilosopher** [comment]
That is a pppwn_cpp problem with the MIPS build needing more work on big endian mips systems, report it to xfangfang with that log and hang tight as they work on the mips build.

**Comment by ukyo13** [comment]
> That is a pppwn_cpp problem with the MIPS build needing more work on big endian mips systems, report it to xfangfang with that log and hang tight as they work on the mips build.

Got it, will send the log there. Thanks!

**Comment by tongduanmingo** [comment]
i have same problem program getting Killed, i thought its because of Less FLASH/RAM

**Comment by tongduanmingo** [comment]
![image](https://github.com/FalsePhilosopher/PPPwnWRT/assets/78008112/b73b7f6f-0e63-4cb5-aebc-dda4c1d4015d)

**Comment by FalsePhilosopher** [comment]
Try `tail -n +1 | pppwn --everything else`
https://superuser.com/questions/554855/how-can-i-fix-a-broken-pipe-error

**Comment by tongduanmingo** [comment]
hello i was having same problem but its fixed by xfangfang latest update with buffer-size feature checkout this
https://github.com/xfangfang/PPPwn_cpp/issues/42

**Comment by Greengoblin007** [comment]
On low-spec devices such as old routers you should try the "--buffer-size 10240" option.
